@startuml

title __SHOPSCREENS's Class Diagram__\n

  package com.madrat.spaceshooter {
    package com.madrat.spaceshooter.screens {
      package com.madrat.spaceshooter.screens.shopscreens {
        class ShopScreenPowerUps {
            - batch : SpriteBatch
            - backBtn : TextButton
            - balance : Label
            - stage : Stage
            - skin : Skin
            - container : Table
            - arrow : Image
            - isHealFullyUpgraded : boolean
            - isAmmoFullyUpgraded : boolean
            - isShieldFullyUpgraded : boolean
            - healUpgradeStage : int
            - ammoUpgradeStage : int
            - shieldUpgradeStage : int
            - money : int
            - currentPlayerState : JsonObject
            - currentPowerUpsState : JsonObject
            + ShopScreenPowerUps()
            - setUpHeal()
            - setUpAmmo()
            - setUpShield()
            - notEnoughMoneySetUp()
            - successfullyBoughtSetUp()
            - setPreviousScreen()
            - addKeyListener()
            - setUpDefaults()
            - setUpIsHealFullyUpgraded()
            - setUpIsAmmoFullyUpgraded()
            - setUpIsShieldFullyUpgraded()
            - getActualData()
            - updateData()
            - getCurrentMoney()
            + show()
            + render()
            + resize()
            + pause()
            + resume()
            + hide()
            + dispose()
        }
      }
    }
  }
  

  package com.madrat.spaceshooter {
    package com.madrat.spaceshooter.screens {
      package com.madrat.spaceshooter.screens.shopscreens {
        class ShopScreenSpaceShips {
            - batch : SpriteBatch
            - backBtn : TextButton
            - balance : Label
            - stage : Stage
            - skin : Skin
            - container : Table
            - arrow : Image
            - money : int
            - currentPlayerState : JsonObject
            - shipStatsJson : JsonObject
            + ShopScreenSpaceShips()
            - displayShip()
            - getActualData()
            - updateData()
            - updateData()
            - getCurrentMoney()
            - notEnoughMoneySetUp()
            - successfullyBoughtSetUp()
            - successfullySelectedSetUp()
            - setPreviousScreen()
            - addKeyListener()
            + show()
            + render()
            + resize()
            + pause()
            + resume()
            + hide()
            + dispose()
        }
      }
    }
  }
  

  ShopScreenPowerUps -up-|> Screen
  ShopScreenPowerUps o-- MainGame : game
  ShopScreenPowerUps o-- ScrollingBackground : scrollingBackground
  ShopScreenPowerUps o-- DialogAlert : notEnoughMoneyDialog
  ShopScreenPowerUps o-- DialogAlert : successfullyBoughtDialog
  ShopScreenSpaceShips -up-|> Screen
  ShopScreenSpaceShips o-- MainGame : game
  ShopScreenSpaceShips o-- ScrollingBackground : scrollingBackground
  ShopScreenSpaceShips o-- DialogAlert : notEnoughMoneyDialog
  ShopScreenSpaceShips o-- DialogAlert : successfullyBoughtDialog
  ShopScreenSpaceShips o-- DialogAlert : successfullySelectedDialog
  ShopScreenSpaceShips o-- InfoDialog : buyDialog
  ShopScreenSpaceShips o-- InfoDialog : currentDialog


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
